export const brands = [
  {
    name: 'Nike, Inc.',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Logo_NIKE.svg/2560px-Logo_NIKE.svg.png',
  },
  {
    name: 'Adidas AG',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Adidas_Logo.svg/2560px-Adidas_Logo.svg.png',
  },
  {
    name: 'Gucci',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/1960s_Gucci_Logo.svg/2560px-1960s_Gucci_Logo.svg.png',
  },
  {
    name: 'Louis Vuitton',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Louis_Vuitton_logo_and_wordmark.svg/2560px-Louis_Vuitton_logo_and_wordmark.svg.png',
  },
  {
    name: 'H&M',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/H%26M-Logo.svg/2560px-H&M-Logo.svg.png',
  },
  {
    name: 'Zara',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Zara_Logo.svg/2560px-Zara_Logo.svg.png',
  },
  {
    name: 'Uniqlo',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/UNIQLO_logo.svg/2560px-UNIQLO_logo.svg.png',
  },
];

export const fashionProducts = [
  // Áo
  'Basic T-Shirt',
  'Graphic T-Shirt',
  'V-Neck T-Shirt',
  'Crew Neck T-Shirt',
  'Long Sleeve T-Shirt',
  'Polo Shirt',
  'Tank Top',
  'Sleeveless Shirt',
  'Dress Shirt',
  'Oxford Shirt',
  'Flannel Shirt',
  'Denim Shirt',
  'Hawaiian Shirt',
  'Linen Shirt',
  'Henley Shirt',

  // Áo khoác
  'Denim Jacket',
  'Leather Jacket',
  'Bomber Jacket',
  'Windbreaker',
  'Rain Jacket',
  'Winter Coat',
  'Parka',
  'Trench Coat',
  'Blazer',
  'Sport Jacket',
  'Varsity Jacket',
  'Puffer Jacket',
  'Down Jacket',
  'Fur Coat',
  'Wool Coat',

  // Quần
  'Jeans',
  'Slim Fit Jeans',
  'Straight Leg Jeans',
  'Skinny Jeans',
  'Cargo Pants',
  'Chino Pants',
  'Dress Pants',
  'Track Pants',
  'Sweatpants',
  'Joggers',
  'Shorts',
  'Cargo Shorts',
  'Bermuda Shorts',
  'Board Shorts',
  'Athletic Shorts',

  // Đồ thể thao
  'Running Shoes',
  'Training Shoes',
  'Basketball Shoes',
  'Tennis Shoes',
  'Soccer Cleats',
  'Athletic Socks',
  'Sport Bra',
  'Compression Shorts',
  'Yoga Pants',
  'Gym Leggings',
  'Workout Tank',
  'Training Jacket',

  // Phụ kiện
  'Baseball Cap',
  'Beanie',
  'Bucket Hat',
  'Fedora Hat',
  'Leather Belt',
  'Canvas Belt',
  'Wallet',
  'Sunglasses',
  'Watch',
  'Bracelet',
  'Necklace',
  'Ring',
  'Scarf',
  'Gloves',
  'Backpack',
  'Messenger Bag',
  'Tote Bag',
  'Clutch Bag',
  'Crossbody Bag',

  // Giày dép
  'Sneakers',
  'Casual Shoes',
  'Dress Shoes',
  'Oxford Shoes',
  'Loafers',
  'Boots',
  'Chelsea Boots',
  'Combat Boots',
  'Ankle Boots',
  'Sandals',
  'Flip Flops',
  'Slippers',

  // Đồ formal
  'Business Suit',
  'Tuxedo',
  'Evening Dress',
  'Cocktail Dress',
  'Wedding Dress',
  'Formal Gown',
  'Formal Shirt',
  'Formal Pants',
  'Bow Tie',
  'Necktie',

  // Đồ lót
  'Boxers',
  'Briefs',
  'Bra',
  'Panties',
  'Undershirt',
  'Thermal Underwear',
  'Lingerie',
  'Swimsuit',
  'Bikini',
  'Swimming Trunks',

  // Đồ ngủ
  'Pajamas',
  'Nightgown',
  'Bathrobe',
  'Sleeping Mask',
  'House Slippers',
];
